chore: ansible galaxy import on release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -197,30 +197,30 @@ jobs:
             git push origin HEAD:main
           fi
 
-  # galaxy-import:
-  #   name: Galaxy Import
-  #   runs-on: ubuntu-24.04
-  #   needs: tag-and-release
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v5
+  galaxy-import:
+    name: Galaxy Import
+    runs-on: ubuntu-24.04
+    needs: tag-and-release
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5
 
-  #     - name: Set up Python
-  #       uses: actions/setup-python@v5
-  #       with:
-  #         python-version: ${{ vars.python-version }}
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
 
-  #     - name: Install Ansible
-  #       shell: sh
-  #       run: pip3 install --no-compile ansible-core
+      - name: Install Ansible
+        shell: sh
+        run: pip3 install --no-compile ansible-core
 
-  #     - name: Trigger a new import on Galaxy
-  #       shell: bash
-  #       run: |-
-  #         REPOSITORY="${{ github.repository }}"
-  #         OWNER_NAME="${REPOSITORY%%/*}"
-  #         REPO_NAME="${REPOSITORY#*/}"
-  #         [ -z '${{ secrets.GALAXY_API_KEY }}' ] && >&2 echo "ERROR: GALAXY_API_KEY is required" && exit 1
-  #         echo "Importing role with owner: $OWNER_NAME, repo: $REPO_NAME"
-  #         ansible-galaxy role import \
-  # --api-key '${{ secrets.GALAXY_API_KEY }}' "$OWNER_NAME" "$REPO_NAME"
+      - name: Trigger a new import on Galaxy
+        shell: bash
+        run: |-
+          REPOSITORY="${{ github.repository }}"
+          OWNER_NAME="${REPOSITORY%%/*}"
+          REPO_NAME="${REPOSITORY#*/}"
+          [ -z '${{ secrets.GALAXY_API_KEY }}' ] && >&2 echo "ERROR: GALAXY_API_KEY is required" && exit 1
+          echo "Importing role with owner: $OWNER_NAME, repo: $REPO_NAME"
+          ansible-galaxy role import \
+            --api-key '${{ secrets.GALAXY_API_KEY }}' "$OWNER_NAME" "$REPO_NAME"
